theme = "lynx"

baseURL = "https://saccharinepurr.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "@SaccharinePurr"
copyright = "Copyright &copy; 2022–2023 SaccharinePurr. All Rights Reserved."

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "@SaccharinePurr"
  image = "icons/saccharinepurr.png"

  links = [
    { onlyfansfree = { href = "https://onlyfans.com/ReifyJoie?ref=14169401", text = "Free OnlyFans" } },
    { onlyfanspremium = { href = "https://onlyfans.com/SaccharinePurr?ref=144615288", text = "Premium VIP OnlyFans" } },
    { manyvids = { href = "https://www.manyvids.com/Profile/1006513997/SaccharinePurr/", text = "ManyVids" } },
    { amazon = { href = "https://www.amazon.com/hz/wishlist/ls/3RTTRT3UE0TCT?tag=trees4-20", text = "Personal Amazon Wishlist" } },
    { amazon = { href = "https://www.amazon.com/hz/wishlist/ls/2ESTCPH686ILV?tag=trees4-20", text = "Dungeon Amazon Wishlist" } },
    { instagram = "https://instagram.com/SaccharinePurr" },
    { fetlife = { href = "https://fetlife.com/users/8415389", text = "FetLife" } },
    { twitter = "https://twitter.com/SaccharinePurr" },
    { reddit = "https://reddit.com/user/SaccharinePurr" },
    { reifyjoiecom = { href = "https://reifyjoie.com", text = "Kink Photography by Reify Joie" } },
    # { email = "mailto:hello@your_domain.com" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
